version: "3"

services:

  jupyter:
    image: guizmo38/jupyter-training:latest
    container_name: 'jupyter'
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./data:/home/jovyan/data
      - ./HDFS:/home/jovyan/HDFS
      - ./Spark:/home/jovyan/Spark

  spark-master:
    image: guizmo38/spark-master:3.2.1-hadoop3.2-python3.7
    container_name: spark-master
    depends_on:
      - namenode
      - datanode1
      - datanode2
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000

  spark-worker-1:
    image: guizmo38/spark-worker:3.2.1-hadoop3.2-python3.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - "SPARK_WORKER_CORES=1"
      - "SPARK_WORKER_MEMORY=1024m"

  spark-worker-2:
    image: guizmo38/spark-worker:3.2.1-hadoop3.2-python3.7
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - "SPARK_WORKER_CORES=1"
      - "SPARK_WORKER_MEMORY=1024m"

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9010:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./hadoop.env
  
  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    ports:
      - "9864:9864"
    env_file:
      - ./hadoop.env

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    restart: always
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    ports:
      - "9865:9864"
    env_file:
      - ./hadoop.env


volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
